import type { Metadata } from "next";
import {Providers} from "./providers";
import "./globals.css";
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Navbar } from "@/Components/navbar";

export const viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en" className='dark' suppressHydrationWarning>
      <body>
        <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
					<div className="relative flex flex-col h-screen">
						<header className="sticky top-0 z-50 w-full">
							<Navbar />
						</header>
						<main className="container mx-auto max-w-7xl pt-16 px-6 flex-grow">
							{children}
              <SpeedInsights />
						</main>
					</div>
			  </Providers>
      </body>
    </html>
  );
}
